"""Migrations must produce the schema the models describe.

A migration and a model set are two descriptions of one thing, so they drift —
someone adds a column to a model, `create_all()` picks it up, every test passes,
and the deployed database is missing it. This is the gate that catches that.

It also runs the migration end to end, because a revision that has never been
executed is a revision that does not work.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
from sqlalchemy import create_engine, inspect

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from deckastra_api.db.session import Base  # noqa: E402 - includes additive table registration

REPO_ROOT = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = REPO_ROOT / "infrastructure" / "database"
ALEMBIC_INI = ALEMBIC_DIR / "alembic.ini"


def run_alembic(args: list[str], database_url: str) -> subprocess.CompletedProcess[str]:
    import os

    env = {**os.environ, "DATABASE_URL": database_url}
    return subprocess.run(
        [sys.executable, "-m", "alembic", "-c", str(ALEMBIC_INI), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        cwd=ALEMBIC_DIR,
        env=env,
        timeout=300,
    )


@pytest.fixture()
def migrated_url(tmp_path) -> str:
    url = f"sqlite:///{tmp_path / 'migrated.db'}"
    result = run_alembic(["upgrade", "head"], url)
    assert result.returncode == 0, f"alembic upgrade failed:\n{result.stderr}"
    return url


def schema_of(url: str) -> dict[str, dict[str, set[str]]]:
    """Tables -> {columns, indexes, foreign keys}, normalized for comparison."""
    engine = create_engine(url)
    inspector = inspect(engine)

    schema: dict[str, dict[str, set[str]]] = {}
    for table in inspector.get_table_names():
        if table == "alembic_version":
            continue
        schema[table] = {
            "columns": {column["name"] for column in inspector.get_columns(table)},
            "indexes": {
                index["name"] for index in inspector.get_indexes(table) if index.get("name")
            },
            "foreign_keys": {
                f"{fk['constrained_columns'][0]}->{fk['referred_table']}"
                for fk in inspector.get_foreign_keys(table)
                if fk.get("constrained_columns")
            },
        }
    engine.dispose()
    return schema


def test_the_migration_runs(migrated_url: str):
    engine = create_engine(migrated_url)
    tables = set(inspect(engine).get_table_names())
    engine.dispose()

    expected = {
        "users",
        "workspaces",
        # Closes doc 05 S1: without it the authorization chain cannot be resolved
        # for anyone but the workspace owner.
        "workspace_members",
        "projects",
        "presentations",
        "presentation_versions",
        "transactions",
    }
    assert expected.issubset(tables)


def test_migrated_schema_matches_the_models(migrated_url: str, tmp_path):
    """The drift gate."""
    direct_url = f"sqlite:///{tmp_path / 'direct.db'}"
    engine = create_engine(direct_url)
    Base.metadata.create_all(engine)
    engine.dispose()

    migrated = schema_of(migrated_url)
    direct = schema_of(direct_url)

    assert set(migrated) == set(direct), "table sets differ between migration and models"

    for table in sorted(direct):
        assert migrated[table]["columns"] == direct[table]["columns"], f"{table}: columns differ"
        assert migrated[table]["indexes"] == direct[table]["indexes"], f"{table}: indexes differ"
        assert (
            migrated[table]["foreign_keys"] == direct[table]["foreign_keys"]
        ), f"{table}: foreign keys differ"


def test_the_migration_is_reversible(tmp_path):
    # A downgrade nobody has run is a downgrade that does not work, which is
    # discovered at exactly the wrong moment.
    url = f"sqlite:///{tmp_path / 'reversible.db'}"

    assert run_alembic(["upgrade", "head"], url).returncode == 0
    result = run_alembic(["downgrade", "base"], url)
    assert result.returncode == 0, f"downgrade failed:\n{result.stderr}"

    engine = create_engine(url)
    remaining = set(inspect(engine).get_table_names()) - {"alembic_version"}
    engine.dispose()
    assert remaining == set(), f"downgrade left tables behind: {remaining}"


def test_no_pending_autogenerated_changes(migrated_url: str):
    """`alembic check` against a migrated database must report nothing to do.

    This is the same drift check from Alembic's own side, and it catches the case
    the schema comparison above cannot: a difference in something the inspector
    normalizes away.
    """
    result = run_alembic(["check"], migrated_url)
    assert result.returncode == 0, (
        "The models have changes not captured in a migration.\n"
        "Run: alembic -c infrastructure/database/alembic.ini revision --autogenerate\n\n"
        f"{result.stdout}\n{result.stderr}"
    )
