"""Ignore rules, ranking and chunking (doc 05 §20).

These decide what a deck can be grounded in. A wrong ignore rule means a slide
cites a lockfile; a wrong ranking means the README loses to five hundred test
helpers; a wrong chunk boundary means a citation points at the middle of a
function.
"""

from __future__ import annotations

import pytest
from deckastra_integrations.ignore import (
    MAX_FILE_BYTES,
    looks_like_secret,
    should_index_content,
    should_index_path,
)
from deckastra_integrations.ranking import (
    chunk_text,
    detect_frameworks,
    language_of,
    rank_file,
    rank_tree,
)


# ---------------------------------------------------------------- ignoring


@pytest.mark.parametrize(
    "path",
    [
        "node_modules/react/index.js",
        "apps/web/node_modules/x/y.ts",
        "vendor/github.com/pkg/errors/errors.go",
        "build/main.js",
        "target/debug/app",
        ".git/config",
        "__pycache__/module.cpython-313.pyc",
        "coverage/lcov-report/index.html",
    ],
)
def test_directories_that_are_never_source_are_skipped(path: str):
    assert not should_index_path(path).indexed


@pytest.mark.parametrize(
    "path",
    [
        "package-lock.json",
        "apps/web/pnpm-lock.yaml",
        "Cargo.lock",
        "go.sum",
    ],
)
def test_lockfiles_are_skipped(path: str):
    # Real text, machine-written. Indexing them spends the budget on nothing and
    # puts a generated file in front of the ranking.
    assert not should_index_path(path).indexed


@pytest.mark.parametrize(
    "path",
    [
        ".env",
        "apps/api/.env.production",
        "config/credentials.json",
        "certs/server.pem",
        "keys/id_rsa",
        "deploy/service-account-prod.json",
    ],
)
def test_anything_that_looks_like_a_secret_is_never_indexed(path: str):
    """The most important rule here.

    An embedding of a private key is a private key in a database, and a retrieved
    chunk of one ends up in a prompt.
    """
    assert looks_like_secret(path)
    decision = should_index_path(path)
    assert not decision.indexed
    assert "secret" in decision.reason.lower()


def test_binaries_and_minified_bundles_are_skipped():
    assert not should_index_path("assets/logo.png").indexed
    assert not should_index_path("static/app.min.js").indexed
    assert not should_index_path("static/app.js.map").indexed


def test_a_huge_file_is_skipped_with_its_size_in_the_reason():
    decision = should_index_path("src/data.ts", MAX_FILE_BYTES + 1)
    assert not decision.indexed
    assert "KB" in decision.reason


def test_ordinary_source_is_indexed():
    for path in ("src/index.ts", "apps/api/main.py", "README.md", "docs/architecture.md"):
        assert should_index_path(path).indexed, path


def test_content_rules_catch_what_the_path_cannot():
    assert not should_index_content("").indexed
    assert not should_index_content("// Code generated by protoc. DO NOT EDIT.\nx").indexed
    # One enormous line is a bundle or a blob, whatever the extension says.
    assert not should_index_content("var a=" + "x" * 5_000).indexed
    assert should_index_content("def hello():\n    return 1\n\n\nprint(hello())").indexed


# ----------------------------------------------------------------- ranking


def test_documentation_outranks_source():
    # A deck about a repository is usually about what its README says it is.
    assert rank_file("README.md").score > rank_file("src/utils/helpers.ts").score
    assert rank_file("docs/architecture.md").score > rank_file("src/utils/helpers.ts").score


def test_manifests_rank_high_because_they_say_what_the_project_is():
    assert rank_file("package.json").score > rank_file("src/components/Button.tsx").score


def test_entry_points_are_recognised_and_explained():
    ranked = rank_file("src/main.py")
    assert ranked.score > rank_file("src/thing.py").score
    # Doc 03 §8: the agent must be able to explain why a file was selected.
    assert "entry point" in ranked.why.lower()


def test_tests_rank_below_what_they_test():
    assert rank_file("src/store.ts").score > rank_file("src/store.test.ts").score


def test_shallow_files_outrank_deep_ones():
    assert rank_file("index.ts").score > rank_file("a/b/c/d/index.ts").score


def test_every_ranked_file_can_explain_itself():
    for ranked in rank_tree([("README.md", 100), ("src/a.ts", 100), ("package.json", 100)]):
        assert ranked.why


def test_ranking_is_deterministic_including_ties():
    entries = [("b.ts", 10), ("a.ts", 10), ("c.ts", 10)]
    first = [file.path for file in rank_tree(entries)]
    second = [file.path for file in rank_tree(list(reversed(entries)))]
    assert first == second


def test_languages_come_from_extensions():
    assert language_of("a.py") == "Python"
    assert language_of("a.tsx") == "TypeScript"
    assert language_of("a.unknownext") == ""


def test_frameworks_are_read_from_manifests_not_guessed():
    frameworks = detect_frameworks(
        {
            "package.json": '{"dependencies": {"react": "^19", "next": "16"}}',
            "pyproject.toml": 'dependencies = ["fastapi>=0.115", "sqlalchemy>=2"]',
        }
    )
    assert "React" in frameworks
    assert "Next.js" in frameworks
    assert "FastAPI" in frameworks
    assert "SQLAlchemy" in frameworks


def test_a_substring_is_not_a_framework():
    # `preact-compat` is not React, and a framework named on a slide is a claim.
    assert "React" not in detect_frameworks({"package.json": '{"deps":{"preact-compat":"1"}}'})


# ---------------------------------------------------------------- chunking


def test_a_chunk_carries_a_line_range_that_matches_the_source():
    text = "\n".join(f"line {number}" for number in range(1, 201))
    chunks = chunk_text("a.py", text)

    assert chunks
    assert chunks[0].start_line == 1
    for chunk in chunks:
        assert chunk.end_line >= chunk.start_line
        # A citation a reader cannot check is not a citation.
        body = "\n".join(text.splitlines()[chunk.start_line - 1 : chunk.end_line])
        assert chunk.text == body


def test_a_reference_is_the_form_provenance_stores():
    chunk = chunk_text("src/a.py", "x = 1\n" * 200)[0]
    assert chunk.reference == f"src/a.py:{chunk.start_line}-{chunk.end_line}"


def test_chunks_split_on_structure_where_there_is_any():
    source = "\n".join(
        [f"def function_{n}():\n" + "\n".join(["    pass"] * 40) for n in range(6)]
    )
    chunks = chunk_text("a.py", source)

    assert len(chunks) > 1
    # A chunk that starts mid-function retrieves badly and reads worse when it is
    # quoted back as evidence.
    starts = [chunk.text.lstrip().startswith("def ") for chunk in chunks]
    assert sum(starts) >= len(chunks) - 1


def test_a_short_file_is_one_chunk():
    chunks = chunk_text("a.py", "def small():\n    return 42\n" * 3)
    assert len(chunks) == 1


def test_an_empty_file_produces_nothing():
    assert chunk_text("a.py", "") == []
    assert chunk_text("a.py", "\n\n\n") == []


def test_chunking_is_deterministic():
    text = "\n".join(f"def f{n}():\n    return {n}" for n in range(80))
    assert [chunk.reference for chunk in chunk_text("a.py", text)] == [
        chunk.reference for chunk in chunk_text("a.py", text)
    ]
