"""Turning an agent's edit intent into patch operations.

The deterministic half of the contextual edit. The agent said *what* should
change about which element; this decides *how*, using the same operation shapes
the editor's own toolbar produces — so an AI edit and a human edit are literally
the same operations, and undo, validation, provenance and autosave are wired up
once (doc 01 §4.7).

Nothing here calls a model. Nothing here writes. It produces operations and hands
them back.
"""

from __future__ import annotations

from typing import Any

from .patch import split_path  # noqa: F401  (kept for symmetry with risk.py's import)


def _rich_text(text: str) -> dict[str, Any]:
    """A RichTextDocument holding one paragraph.

    Ids are generated by the caller's id function so a replacement block is a new
    block rather than a mutated one — block ids are stable identity, and reusing
    one would make a diff claim the text was edited in place when it was replaced.
    """
    from .ids import new_id

    return {
        "version": 1,
        "blocks": [
            {"id": new_id("blk"), "type": "paragraph", "spans": [{"text": line}]}
            for line in (text.split("\n") or [""])
        ],
    }


def _locate(document: dict[str, Any], element_id: str) -> tuple[dict[str, Any], str, list[str]] | None:
    """Find an element, its slide, and the group ids above it.

    The ancestor chain is what makes an id-addressed path: an element inside a
    group lives at `/slides/id:s/elements/id:g/children/id:e`, and a path that
    skips the group does not resolve.
    """

    def walk(
        elements: list[dict[str, Any]], slide_id: str, ancestors: list[str]
    ) -> tuple[dict[str, Any], str, list[str]] | None:
        for element in elements:
            if element.get("id") == element_id:
                return element, slide_id, ancestors
            if element.get("type") == "group":
                found = walk(element.get("children") or [], slide_id, [*ancestors, element["id"]])
                if found:
                    return found
        return None

    for slide in document.get("slides") or []:
        found = walk(slide.get("elements") or [], slide.get("id", ""), [])
        if found:
            return found
    return None


def _container_path(slide_id: str, ancestors: list[str]) -> str:
    path = f"/slides/id:{slide_id}/elements"
    for group_id in ancestors:
        path += f"/id:{group_id}/children"
    return path


class EditTranslationError(ValueError):
    """An edit that cannot be turned into an operation, with the reason."""


def operations_for_edit(document: dict[str, Any], edit: dict[str, Any]) -> list[dict[str, Any]]:
    """One edit intent -> patch operations.

    Raises rather than skipping. An edit the user was shown a reason for must
    either happen or be reported as impossible; quietly producing no operation
    would leave a preview that promises a change nothing delivers.
    """
    element_id = edit.get("element_id", "")
    located = _locate(document, element_id)
    if located is None:
        raise EditTranslationError(f"Element {element_id} is not on this deck.")

    element, slide_id, ancestors = located
    base = _container_path(slide_id, ancestors)
    element_path = f"{base}/id:{element_id}"
    change = edit.get("change")

    if change == "text":
        new_text = edit.get("new_text", "")
        if not new_text:
            raise EditTranslationError("A text change needs replacement text.")

        # A shape carries its label in `text`; everything else in `content`. Using
        # the wrong key writes a field the renderer does not read, which looks
        # like the edit silently did nothing.
        field = "text" if element.get("type") == "shape" else "content"
        return [{"op": "replace", "path": f"{element_path}/{field}", "value": _rich_text(new_text)}]

    if change == "role":
        role = edit.get("new_role", "")
        if not role:
            raise EditTranslationError("A role change needs a role.")
        operation = "replace" if element.get("semanticRole") else "add"
        return [{"op": operation, "path": f"{element_path}/semanticRole", "value": role}]

    if change == "delete":
        return [{"op": "remove", "path": element_path}]

    if change == "reorder":
        to_index = int(edit.get("to_index", -1))
        if to_index < 0:
            raise EditTranslationError("A reorder needs a target position.")

        siblings = _siblings(document, slide_id, ancestors)
        # Clamped rather than rejected: "move it to the front" from a model that
        # counted wrong should still move it to the front.
        to_index = max(0, min(to_index, len(siblings) - 1))
        return [{"op": "move", "from": element_path, "path": f"{base}/{to_index}"}]

    raise EditTranslationError(f"Unknown change kind {change!r}.")


def _siblings(document: dict[str, Any], slide_id: str, ancestors: list[str]) -> list[dict[str, Any]]:
    for slide in document.get("slides") or []:
        if slide.get("id") != slide_id:
            continue
        elements = slide.get("elements") or []
        for group_id in ancestors:
            group = next((e for e in elements if e.get("id") == group_id), None)
            if group is None:
                return []
            elements = group.get("children") or []
        return elements
    return []


def operations_for_plan(
    document: dict[str, Any], plan: dict[str, Any]
) -> tuple[list[dict[str, Any]], list[str], list[dict[str, Any]]]:
    """A whole edit plan -> operations, problems, and the reasons to show.

    Returns three things because the caller needs all three: the operations to
    propose, the edits that could not be translated (reported, never swallowed),
    and the per-edit reasons that go next to the preview.
    """
    operations: list[dict[str, Any]] = []
    problems: list[str] = []
    reasons: list[dict[str, Any]] = []

    for edit in plan.get("edits") or []:
        try:
            produced = operations_for_edit(document, edit)
        except EditTranslationError as error:
            problems.append(str(error))
            continue

        operations.extend(produced)
        reasons.append(
            {
                "element_id": edit.get("element_id", ""),
                "change": edit.get("change", ""),
                "reason": edit.get("reason", ""),
            }
        )

    return operations, problems, reasons
