"""sharing, quotas, assets and themes

Revision ID: 76226b0ee21d
Revises: e6f9e3ffab16
Create Date: 2026-09-06 03:23:56.685131
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic renders JSONB as `postgresql.JSONB(astext_type=Text())` without importing
# Text, so the import is provided here rather than hand-added to every revision.
from sqlalchemy import Text  # noqa: F401

from sqlalchemy.dialects import postgresql

revision: str = '76226b0ee21d'
down_revision: str | None = 'e6f9e3ffab16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'video', 'audio', 'font', 'document')", name='ck_asset_kind'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_orphans', 'assets', ['reference_count', 'deleted_at'], unique=False)
    op.create_index('ix_assets_workspace', 'assets', ['workspace_id', 'deleted_at'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_theme_name')
    )
    op.create_index('ix_themes_workspace', 'themes', ['workspace_id', 'archived_at'], unique=False)
    op.create_table('workspace_quotas',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('monthly_generations', sa.Integer(), nullable=True),
    sa.Column('monthly_tokens', sa.Integer(), nullable=True),
    sa.Column('storage_bytes', sa.Integer(), nullable=True),
    sa.Column('max_repositories', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_generations', sa.Integer(), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.Column('used_storage_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('presentation_shares',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'editor')", name='ck_share_role'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_share_token')
    )
    op.create_index('ix_shares_presentation', 'presentation_shares', ['presentation_id', 'revoked_at'], unique=False)
    # Autogenerate proposes dropping `repository_chunks.embedding` and its HNSW
    # index on every revision, and it is wrong every time: the column is a
    # PostgreSQL-only `vector` added by raw SQL in the Phase 6 revision, and the
    # models cannot declare it because `vector` has no SQLite equivalent.
    #
    # Taking the suggestion would drop the semantic index on every deployment
    # that migrates — silently, because retrieval falls back to the JSON path and
    # keeps returning results.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # See upgrade(): the embedding column is not this revision's to restore.
    op.drop_index('ix_shares_presentation', table_name='presentation_shares')
    op.drop_table('presentation_shares')
    op.drop_table('workspace_quotas')
    op.drop_index('ix_themes_workspace', table_name='themes')
    op.drop_table('themes')
    op.drop_index('ix_assets_workspace', table_name='assets')
    op.drop_index('ix_assets_orphans', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
