"""export jobs

Revision ID: e6f9e3ffab16
Revises: 82df959ba119
Create Date: 2026-09-06 02:54:49.199125
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic renders JSONB as `postgresql.JSONB(astext_type=Text())` without importing
# Text, so the import is provided here rather than hand-added to every revision.
from sqlalchemy import Text  # noqa: F401

from sqlalchemy.dialects import postgresql

revision: str = 'e6f9e3ffab16'
down_revision: str | None = '82df959ba119'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('pdf', 'pptx')", name='ck_export_kind'),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_export_status'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_jobs_presentation', 'export_jobs', ['presentation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate proposed dropping `repository_chunks.embedding` and its HNSW
    # index. That is wrong, and it will keep proposing it: the column is a
    # PostgreSQL-only `vector` added by raw SQL in the previous revision, and the
    # models cannot declare it because `vector` has no SQLite equivalent. Alembic
    # sees a column with no model behind it and concludes it was removed.
    #
    # Deleting it here would drop the semantic index on every deployment that
    # runs a migration — silently, because retrieval falls back to the JSON path
    # and still returns results. The drop is removed rather than reordered.


def downgrade() -> None:
    # Only this revision's own table. The `embedding` column belongs to the
    # previous revision and re-creating it here would be this migration
    # undoing something it never did.
    op.drop_index('ix_export_jobs_presentation', table_name='export_jobs')
    op.drop_table('export_jobs')
