"""agent runs, memory and proposal expiry

Revision ID: fcc98f773800
Revises: 5f70aef2912e
Create Date: 2026-09-05 18:40:36.683221
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic renders JSONB as `postgresql.JSONB(astext_type=Text())` without importing
# Text, so the import is provided here rather than hand-added to every revision.
from sqlalchemy import Text  # noqa: F401

from sqlalchemy.dialects import postgresql

revision: str = 'fcc98f773800'
down_revision: str | None = '5f70aef2912e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('accepted_layout', 'rejected_proposal', 'dismissed_issue', 'preference')", name='ck_agent_memory_kind'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_memory', schema=None) as batch_op:
        batch_op.create_index('ix_agent_memory_project', ['project_id', 'created_at'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('presentation_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('scope_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('warnings_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('errors_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('budget_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'awaiting_approval', 'completed', 'failed', 'exhausted', 'cancelled')", name='ck_agent_run_status'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index('ix_agent_runs_presentation', ['presentation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_presentation_id'), ['presentation_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('run_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_run_id'))
        batch_op.drop_column('run_id')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_presentation_id'))
        batch_op.drop_index('ix_agent_runs_presentation')

    op.drop_table('agent_runs')
    with op.batch_alter_table('agent_memory', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_memory_project')

    op.drop_table('agent_memory')
    # ### end Alembic commands ###
