"""github installations, repositories and chunks

Revision ID: 82df959ba119
Revises: fcc98f773800
Create Date: 2026-09-05 21:38:44.381618
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic renders JSONB as `postgresql.JSONB(astext_type=Text())` without importing
# Text, so the import is provided here rather than hand-added to every revision.
from sqlalchemy import Text  # noqa: F401

from sqlalchemy.dialects import postgresql

revision: str = '82df959ba119'
down_revision: str | None = 'fcc98f773800'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('github_installation_id', sa.String(length=64), nullable=False),
    sa.Column('account_login', sa.String(length=128), nullable=False),
    sa.Column('installed_by', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_installation_id', name='uq_github_installation')
    )
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.create_index('ix_github_installations_workspace', ['workspace_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('github_repository_id', sa.String(length=64), nullable=True),
    sa.Column('default_branch', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('index_status', sa.String(length=16), nullable=False),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('indexed_sha', sa.String(length=64), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('embedding_semantic', sa.Boolean(), nullable=False),
    sa.Column('profile_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('warnings_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("index_status IN ('pending', 'indexing', 'ready', 'failed', 'revoked')", name='ck_repository_index_status'),
    sa.CheckConstraint("source IN ('github', 'local')", name='ck_repository_source'),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'full_name', name='uq_repository_per_workspace')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index('ix_repositories_workspace', ['workspace_id'], unique=False)

    op.create_table('repository_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_sha', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('embedding_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_repository_chunks_path', ['repository_id', 'path'], unique=False)
        batch_op.create_index('ix_repository_chunks_repository', ['repository_id'], unique=False)

    # ### end Alembic commands ###


    # pgvector: the fast retrieval path (gap register doc 05 S2).
    #
    # PostgreSQL only, and conditional even there. `embedding_json` is the
    # portable source of truth — it works on SQLite and survives the extension
    # being unavailable on a managed instance — and this column is a derived
    # index over it. Keeping both costs a little storage; keeping only the vector
    # would mean local development required PostgreSQL.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute("ALTER TABLE repository_chunks ADD COLUMN embedding vector(1024)")
        # HNSW rather than IVFFlat: it needs no training pass, so an index built
        # on an empty table stays correct as rows arrive. IVFFlat built before the
        # data exists silently returns poor neighbours.
        op.execute(
            "CREATE INDEX ix_repository_chunks_embedding "
            "ON repository_chunks USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_repository_chunks_embedding")
        # The extension is left in place: another table may use it, and dropping
        # a shared extension on the way down is a surprise nobody wants.
    with op.batch_alter_table('repository_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_repository_chunks_repository')
        batch_op.drop_index('ix_repository_chunks_path')

    op.drop_table('repository_chunks')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index('ix_repositories_workspace')

    op.drop_table('repositories')
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.drop_index('ix_github_installations_workspace')

    op.drop_table('github_installations')
    # ### end Alembic commands ###
